services:
  db:
    container_name: db_planning
    image: postgres:15
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - pgdata_planning:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d warehouse_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend_planning
    build: ./backend
    ports:
      - "8081:8080" 
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=warehouse_db;Username=admin;Password=password123

  frontend:
    container_name: frontend_planning
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5174:5173"
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend

  pgadmin:
    container_name: pgadmin_planning
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

  rabbitmq:
    container_name: rabbitmq_planning
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata_planning:
